name: Deploy Backend

run-name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to PROD VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /var/www/salon_backend_apis/SALON_SERVICES

            git pull origin main

            npm install

            APP_ENV=production NODE_ENV=production npx sequelize-cli db:migrate

            pm2 restart SALON_API --update-env
